package sen.khyber.util;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Map;

public class SuperListMapMixin<K, V> extends SuperList<V> {
    
    /**
     * generated by eclipse
     */
    private static final long serialVersionUID = -5813528328081259375L;
    
    protected Collection<Map<? super K, ? super V>> superMaps;
    
    private Collection<Collection<? super V>> superValueColls;
    
    public SuperListMapMixin(Collection<Collection<? super V>> superColls, 
            Collection<Map<? super K, ? super V>> superMaps) {
        super.superColls = superColls;
        this.superMaps = superMaps;
        superValueColls = new ArrayList<>();
        for (Map<? super K, ? super V> superMap : superMaps) {
            superValueColls.add(superMap.values());
        }
    }
    
    public boolean addWithKey(K key, V value) {
        super.add(value);
        for (Map<? super K, ? super V> superMap : superMaps) {
            superMap.put(key, value);
        }
        return true;
    }
    
    @Override
    public boolean remove(Object obj) {
        for (Collection<? super V> superValueColl : superValueColls) {
            superValueColl.remove(obj);
        }
        return super.remove(obj);
    }
    
    public void linkMap(Map<? super K, ? super V> superMap) {
        superMaps.add(superMap);
    }
    
}
