package sen.khyber.util;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;

public class SuperList<E> extends ArrayList<E> {
    
    /**
     * randomly generated by eclipse
     */
    private static final long serialVersionUID = 2732888534285675100L;
    
    protected Collection<Collection<? super E>> superColls;
    
    public SuperList(Collection<Collection<? super E>> superColls) {
        this.superColls = superColls;
    }
    
    @SafeVarargs
    public SuperList(Collection<? super E>... superColls) {
        this.superColls = new ArrayList<>(Arrays.asList(superColls));
    }
    
    @Override
    public boolean add(E e) {
        super.add(e);
        for (Collection<? super E> superList : superColls) {
            superList.add(e);
        }
        return true;
    }
    
    @Override
    public boolean remove(Object obj) {
        for (Collection<? super E> superList : superColls) {
            superList.remove(obj);
        }
        return super.remove(obj);
    }
    
    public void linkCollection(Collection<? super E> superColl) {
        superColls.add(superColl);
    }
    
}