package sen.khyber.util;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Map;

/**
 * 
 * 
 * @author Khyber Sen
 * @param <K> key type
 * @param <V> value type
 */
public class SuperListMapMixin<K, V> extends SuperList<V> {
    
    /**
     * generated by eclipse
     */
    private static final long serialVersionUID = -5813528328081259375L;
    
    protected Collection<Map<? super K, ? super V>> superMaps;
    
    private final Collection<Collection<? super V>> superValueColls;
    
    public SuperListMapMixin(final Collection<Collection<? super V>> superColls,
            final Collection<Map<? super K, ? super V>> superMaps) {
        super.superColls = superColls;
        this.superMaps = superMaps;
        superValueColls = new ArrayList<>();
        for (final Map<? super K, ? super V> superMap : superMaps) {
            superValueColls.add(superMap.values());
        }
    }
    
    public boolean addWithKey(final K key, final V value) {
        super.add(value);
        for (final Map<? super K, ? super V> superMap : superMaps) {
            superMap.put(key, value);
        }
        return true;
    }
    
    @Override
    public boolean remove(final Object obj) {
        for (final Collection<? super V> superValueColl : superValueColls) {
            superValueColl.remove(obj);
        }
        return super.remove(obj);
    }
    
    public void linkMap(final Map<? super K, ? super V> superMap) {
        superMaps.add(superMap);
    }
    
}
